### ISSUE TITLE
Games com

### ISSUE THREAD

**Issue by casparss** [casparss/racket-meetup-mobile#19]
## Challenge
Now the availability component is working and meshing both users availabilities, the date and time selection should be integrated into it with the following inputs and behaviour:
- Week commencing select with the following values: "this week", "next week", "w/c 22nd July", "w/c 29th July"
- Day of the week select ("Monday", "Tuesday" etc.), when selecting a day, the availability mesh should remove or block out unselected days
- Select for time of day with values: "morning", afternoon" and "evening". The available values are dependent on the availability mesh.
- Time select which has only the time ranges that are selected in the availability mesh.
### Todos
- [x] Week commencing select
- [x] Day of the week select
- [x] Select for time of day
- [x] Time select

## Games summary
Profile screen now needs to show 3 upcoming games/events max with a show more button to access the full games screen below. The games card needs to be a miniature list style version like the left design here https://www.pinterest.com/pin/562668547180055498/ 

Clicking on a game card on either profile or games screen will open up the game instance itself. There should also be a view more button at the bottom. Also, there should be a games action that takes you to that players games.

### Todos
- [x] View more button created at bottom of summary
- [x] Decide whether to reuse challenge.component or to modulurise reusable components and create a new edit screen which reuses all the other components
- [ ] Clicking on game instance button goes through to game instance
- [ ] Remove ugly masking on lists that can be seen when clicking on game instance button

## All games
All Games is now covered under it's own ticket #26

## View game
The game instance screen will be similar to the challenge screen, with some action buttons with: Cancel, played/record result, comment. Will also want an activity component displaying all pertinent activity such as edits/change details, comments, recording score, cancellations etc.

### Todos
- [ ] Record match results
- [ ] Change match arrangements

Stretch goals
- [ ] Think about game activity feed to track changes, comments, recording match history etc
- [ ] web sockets for real time update of game status
- [ ] lazy loading
- [ ] once past game date, then state should change to a 'played-pending-result'
- [ ] game activity feed
- [ ] comments, which go onto the activity feed

### Badges
To make the user aware of pending games, badges applied to the 'Profile' tab button on the main menu and to the 'Games' 'Actions' button on the 'Profile' tab. The badge count will represent the number of games that need attention i.e. that are awaiting action from you. Games that are awaiting action from other users will not be counted. Perhaps a second green badge on the 'Games' 'Actions' button representing upcoming games might be cool too and even further a yellow bad representing games that are pending other user actions might be cool, but also might be confusing so need to test out.

### Todos
- [ ] Create list when starting this task

**Comment by casparss** [comment]
Closing, feature is nearly complete con pledge, pick up last bits in big ticket
